# Generated by Django 4.0.2 on 2022-02-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pool', to='webapp.poll', verbose_name='Опрос'),
            preserve_default=False,
        ),
    ]
